CREATE DATABASE IF NOT EXISTS feedback_db;

USE feedback_db;

CREATE TABLE IF NOT EXISTS feedback(
    id INT AUTO_INCREMENT PRIMARY KEY,
    Student_name VARCHAR(100),
    Emial VARCHAR(100),
    comments TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);